events {}

http {
    upstream my_cluster {
        server dashboard:80; # Docker DNS handles the multiple replicas automatically!
    }

    server {
        listen 80;

        location / {
            proxy_pass http://my_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
